name: Scheduled Run

on:
 workflow_dispatch:
 schedule:
    - cron: 30 18 * * 1-5
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Check out the repo, so the job can access it.  
      - uses: actions/checkout@v4
 
      # Install Node on the runner
      - name: Use Node.js      
        uses: actions/setup-node@v3
       
      # Install newman globally, and install the html extra reporter
      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
 
      # Run postman collection
      - name: Run Postman Collection and Generate HTML Report
        run: 'newman run Trello.postman_collection.json --reporters cli,htmlextra --reporter-htmlextra-export report.html'
      
      # Make sure that the report has been created
      - name: Chech Files
        run: 'ls' 
        
      # Upload the reports to TestArtifacts directory
      - name: Output the results
        if: always()
        uses: actions/upload-artifact@v3
        with:
         name: Reports
         path: "*html"

      - name: Send report via email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          to: serpol.jb87@gmail.com
          subject: Test Report
          from: GitHub Actions <actions@example.com>
          attachments: report.html
