name: Scheduled Run

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose Environment for Test Run'
        required: true
        # --- ИЗМЕНЕНО: 'test' (Stage) теперь по умолчанию ---
        default: 'test'
        type: 'choice'
        options:
          - prod
          - test 
      os:
        description: 'Choose Operating System'
        required: true
        default: 'ubuntu'
        type: 'choice'
        options:
          - ubuntu
          - windows
          
  schedule:
    - cron: '30 18 * * 1-5'
    
jobs:
  build:
    runs-on: ${{ inputs.os == 'windows' && 'windows-latest' || 'ubuntu-latest' }}

    # --- ДОБАВЛЕНО: Динамическая переменная для файла окружения ---
    env:
      # Логика: Если выбран 'prod', берем Prod-файл.
      # Во всех остальных случаях (включая 'test' и 'schedule') - берем Stage-файл.
      ENV_FILE: ${{ inputs.environment == 'prod' && 'Trello_Env_Prod.postman_environment.json' || 'Trello_Env_Stage.postman_environment.json' }}
    
    steps:
      - uses: actions/checkout@v4
  
      - name: Use Node.js      
        uses: actions/setup-node@v3
        
      - name: Install newman
        shell: bash
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
  
      # --- ИЗМЕНЕНО: Команда Newman теперь использует переменную $ENV_FILE ---
      - name: Run Postman Collection and Generate HTML Report
        shell: bash
        # Добавлен флаг '-e $ENV_FILE'
        run: 'newman run Trello.postman_collection.json -e $ENV_FILE --reporters cli,htmlextra --reporter-htmlextra-export report.html'
      
      - name: Check Files
        shell: bash
        run: 'ls' 
        
      - name: Output the results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Reports
          path: "*html"
